### ISSUE TITLE
Having some troubles with an otherwise perfect node

### ISSUE THREAD

**Issue by MissingCat69** [meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi#3] opened 2020-04-07 08:48 UTC
I need to take one or two readings from the device, but stacking as per the example seems to drop the second request immediately. I tried to remedy this with a delay node but it seems to keep doing it.

Other issues I picked up is that the sps seem to be locked to 128 in the menu, but set to 250 when observed in the exported node. I managed to edit this in a text file and put it back in but it still reflects as 128 sps in the menu.

I it possible to add current to this instead of voltage as an option, for the LCS712. mvA to the three available models are 185mva for the 5A, 100mva for the 20A and 66mva for the 30A.

The math for this can be found at https://www.sparkfun.com/datasheets/BreakoutBoards/0712.pdf

**Comment by meeki007** [comment] 2020-04-07 14:52
Looking at code for the 128 samples per second issue now. Then tonight when I get home I can pull out my unit and start testing on the second request drop msg when stacking issue.

LCS712 current node........After I get the bugs you found fixed in this node,  I'll take a look at the current chip. More likely get an answer on current chip node this weekend when I have time to dig deep on it. Looks cool.

**Comment by MissingCat69** [comment] 2020-04-07 17:38
Thank you for having a look at it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by meeki007** [comment] 2020-04-08 22:12
I have fixed the samples per second for the html side of things
if you wish to see the changes please see
[https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/pull/5/files](https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/pull/5/files)

My html side of things always is a challenge. I just moved things into a more concise if statement and then my brain was able to see all the mistakes. I never messed with the samples per second when I wrote this node. Sorry to all who have been stuck at 250 samples per second.

Well onto the JS side of the code now.

**Comment by meeki007** [comment] 2020-04-08 22:40
I have fixed the samples per second for the JS side of things
if you wish to see the changes please see
[https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/pull/6/files](https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/pull/6/files)

**Comment by meeki007** [comment] 2020-04-08 22:45
I think your issue, "....but stacking as per the example seems to drop the second request immediately"
is caused by not changing the msg.payload name to something unique for each node. If you import my example for the advanced node you will see the msg property has been changed for each one. 
```
[{"id":"9fa062dc.6e1b6","type":"inject","z":"a074224d.a6b91","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":240,"wires":[["2bfc185d.72ddd8"]]},{"id":"2bfc185d.72ddd8","type":"ads1x15-raspi","z":"a074224d.a6b91","property":"x48_A0-GND","name":"x48_A0-GND","chip":"IC_ADS1115","i2c_address":"ADDRESS_0x48","channel":"CHANNEL_0","samplesPerSecond":"SPS_250","progGainAmp":"PGA_4_096V","x":350,"y":140,"wires":[["e219cd74.4ea59"]]},{"id":"edb67462.6fbb88","type":"debug","z":"a074224d.a6b91","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":220,"wires":[]},{"id":"e219cd74.4ea59","type":"ads1x15-raspi","z":"a074224d.a6b91","property":"x48_A1-GND","name":"x48_A1-GND","chip":"IC_ADS1115","i2c_address":"ADDRESS_0x48","channel":"CHANNEL_1","samplesPerSecond":"SPS_250","progGainAmp":"PGA_4_096V","x":350,"y":200,"wires":[["bc5b5300.34dc1"]]},{"id":"bc5b5300.34dc1","type":"ads1x15-raspi","z":"a074224d.a6b91","property":"x48_A2-GND","name":"x48_A2-GND","chip":"IC_ADS1115","i2c_address":"ADDRESS_0x48","channel":"CHANNEL_2","samplesPerSecond":"SPS_250","progGainAmp":"PGA_4_096V","x":350,"y":260,"wires":[["6a55c7a6.54e078"]]},{"id":"6a55c7a6.54e078","type":"ads1x15-raspi","z":"a074224d.a6b91","property":"x48_A3-GND","name":"x48_A3-GND","chip":"IC_ADS1115","i2c_address":"ADDRESS_0x48","channel":"CHANNEL_3","samplesPerSecond":"SPS_250","progGainAmp":"PGA_4_096V","x":350,"y":320,"wires":[["edb67462.6fbb88"]]}]
```

I'm working on a fix for that now as people may over look that. Basically your over writing the msg each time.

**Comment by meeki007** [comment] 2020-04-09 02:59
update pushed to NPM. You should see an option to update your version in less than an hour.

I had to reboot the pi not just node red for it to update the html side of things. also I had an issue with firefox cashing the old info and making me think the code was broken.

**Comment by MissingCat69** [comment] 2020-04-09 06:34
Thank you so much. Looking forward to seeing your other projects.

Regards,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2020-04-09 16:53 UTC
